# Generated by Django 5.2.6 on 2025-09-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_paper', models.FileField(upload_to='uploads/question_papers/')),
                ('model_answer', models.FileField(upload_to='uploads/model_answers/')),
                ('student_answers', models.FileField(upload_to='uploads/student_answers/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
