# Generated by Django 5.2.6 on 2025-10-03 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading_app', '0002_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Grading'), ('GRADED', 'Graded'), ('FAILED', 'Grading Failed')], default='PENDING', max_length=10),
        ),
        migrations.CreateModel(
            name='GradingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_json', models.JSONField(default=list)),
                ('full_gemini_response', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grading_result', to='grading_app.upload')),
            ],
        ),
    ]
