# Generated by Django 5.2.6 on 2025-10-03 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading_app', '0003_upload_status_gradingresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='status',
        ),
        migrations.AddField(
            model_name='upload',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='upload',
            name='model_answer',
            field=models.FileField(upload_to='uploads/answers/'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='question_paper',
            field=models.FileField(upload_to='uploads/questions/'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='student_answers',
            field=models.FileField(upload_to='uploads/students/'),
        ),
    ]
