# Generated by Django 5.2.6 on 2025-10-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading_app', '0004_remove_upload_status_upload_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='status',
            field=models.CharField(choices=[('N', 'Not Processed'), ('GRADED', 'Graded'), ('FAILED', 'Failed')], default='N', max_length=20),
        ),
    ]
